/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Verifies email/password and sets the auth cookie. Returns 200 with the user, or 401 if the credentials are wrong.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a customer
         * @description Creates a Customer account and signs them in. 400 on invalid input, 409 if the email is taken.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Clears the auth cookie. Always returns 204.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Returns the signed-in user, or 401 if there's no active session.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all orders
         * @description Returns every order, newest first, with the customer's email. Use it to see an order flip from Pending to Paid after a webhook.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Start a checkout
         * @description Creates a Pending order (with its line items) and a matching Stripe PaymentIntent, then returns the clientSecret the frontend uses to confirm the card.
         *
         *     Body: currency (lowercase ISO code, e.g. "eur") and items[] (each with productId, title, unitAmountCents, quantity). The charged total is the sum of the items.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateOrderResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one order with its line items
         * @description Returns a single order plus the products it contains and its Stripe PaymentIntent id. Powers the admin order-detail page.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderDetailResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refund a paid order
         * @description Asks Stripe to refund the order's payment. Returns 202 Accepted immediately; the order flips to Refunded only when the charge.refunded webhook arrives. Fails with 404 if the order doesn't exist, or 400 if it isn't Paid.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefundResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Returns 200 with { status: "ok" } if the API is up. No parameters.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["String<>f__AnonymousType6"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe webhook receiver
         * @description Called by Stripe (not by the frontend). Requires a valid 'Stripe-Signature' header; the raw body is verified against the webhook secret.
         *
         *     You cannot produce a valid call from Swagger — use the Stripe CLI (`stripe listen` + `stripe trigger`). Calling it here returns 400 (no valid signature), which demonstrates the forged-request rejection.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body to start a checkout. The charged total is the sum of the items. */
        CreateOrderRequest: {
            /** @description Lowercase ISO currency code. Example: "eur". */
            currency?: string | null;
            /** @description The line items being purchased (at least one). */
            items?: components["schemas"]["OrderItemInput"][] | null;
        };
        /** @description Response returned when a checkout starts. */
        CreateOrderResponse: {
            /**
             * Format: uuid
             * @description The new order's id.
             */
            orderId?: string;
            /** @description The Stripe clientSecret the frontend uses to confirm the card. */
            clientSecret?: string | null;
            /**
             * Format: int64
             * @description Amount in the smallest currency unit (cents).
             */
            amountCents?: number;
            /** @description Lowercase ISO currency code, e.g. "eur". */
            currency?: string | null;
        };
        /** @description Credentials for POST /auth/login. */
        LoginRequest: {
            /** @description Account email (case-insensitive). */
            email?: string | null;
            /** @description Account password (plaintext over HTTPS; verified against a stored hash). */
            password?: string | null;
        };
        /** @description Full detail of one order, including its line items — the admin detail view. */
        OrderDetailResponse: {
            /**
             * Format: uuid
             * @description The order id.
             */
            id?: string;
            /**
             * Format: int64
             * @description Total amount in the smallest currency unit (cents).
             */
            amountCents?: number;
            /** @description Lowercase ISO currency code, e.g. "eur". */
            currency?: string | null;
            status?: components["schemas"]["OrderStatus"];
            /**
             * Format: date-time
             * @description When the order was created (UTC).
             */
            createdAt?: string;
            /** @description Email of the account that placed it, or null if none. */
            customerEmail?: string | null;
            /** @description The Stripe PaymentIntent id (deep-link to the Stripe dashboard). */
            stripePaymentIntentId?: string | null;
            /** @description The products purchased. */
            items?: components["schemas"]["OrderItemResponse"][] | null;
        };
        /** @description One line item in a checkout request. */
        OrderItemInput: {
            /**
             * Format: int32
             * @description The catalog (DummyJSON) product id. 0 for the admin's manual charge.
             */
            productId?: number;
            /** @description The product title, shown later in the order detail. */
            title?: string | null;
            /**
             * Format: int64
             * @description Unit price in the smallest unit of the order currency (cents).
             */
            unitAmountCents?: number;
            /**
             * Format: int32
             * @description How many of this product (positive integer).
             */
            quantity?: number;
            /** @description Optional product image URL. */
            thumbnail?: string | null;
        };
        /** @description One line item as returned in an order's detail. */
        OrderItemResponse: {
            /**
             * Format: int32
             * @description The catalog product id (0 for a manual charge).
             */
            productId?: number;
            /** @description The product title snapshot. */
            title?: string | null;
            /**
             * Format: int64
             * @description Unit price in the smallest currency unit (cents).
             */
            unitAmountCents?: number;
            /**
             * Format: int32
             * @description How many of this product.
             */
            quantity?: number;
            /** @description Product image URL, or null. */
            thumbnail?: string | null;
        };
        /** @description An order as shown in the admin list, with the customer who placed it. */
        OrderResponse: {
            /**
             * Format: uuid
             * @description The order id.
             */
            id?: string;
            /**
             * Format: int64
             * @description Amount in the smallest currency unit (cents).
             */
            amountCents?: number;
            /** @description Lowercase ISO currency code, e.g. "eur". */
            currency?: string | null;
            status?: components["schemas"]["OrderStatus"];
            /**
             * Format: date-time
             * @description When the order was created (UTC).
             */
            createdAt?: string;
            /** @description Email of the account that placed it, or null if none. */
            customerEmail?: string | null;
        };
        /** @enum {string} */
        OrderStatus: "Pending" | "Paid" | "Failed" | "Refunded";
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** @description Response returned when a refund is accepted (still pending). */
        RefundResponse: {
            /**
             * Format: uuid
             * @description The order being refunded.
             */
            orderId?: string;
            /** @description Always "refund_pending" — the order flips to Refunded only on the charge.refunded webhook. */
            status?: string | null;
            /** @description Human-readable explanation the frontend can show. */
            message?: string | null;
        };
        /** @description Details for POST /auth/register. */
        RegisterRequest: {
            /** @description The new account's email (must be unique). */
            email?: string | null;
            /** @description The new account's password (min 6 chars). */
            password?: string | null;
        };
        "String<>f__AnonymousType6": {
            status?: string | null;
        };
        /** @description The signed-in user, returned by login and /auth/me. */
        UserResponse: {
            /** @description The user's email. */
            email?: string | null;
            role?: components["schemas"]["UserRole"];
        };
        /** @enum {string} */
        UserRole: "Customer" | "Admin";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
