// Single place that knows where the backend lives. The data TYPES come from the
// backend's OpenAPI contract (src/api-types.ts, generated by `npm run gen:api`) —
// no hand-maintained copy that can silently drift from the API.

import type { components } from "./api-types";

// Where the backend lives. Both in the production monolith AND in dev (via the
// Vite proxy, see vite.config.ts) the API and SPA share one origin, so the base is
// "" (same-origin, relative fetches). Same-origin is what lets the auth cookie flow
// automatically. Override with VITE_API_BASE only if you split FE and BE onto
// separate hosts (then you also need CORS with credentials on the backend).
const configuredBase = import.meta.env.VITE_API_BASE as string | undefined;
export const API_BASE = configuredBase ?? "";

// Every request opts into sending/receiving cookies. Same-origin would send them
// anyway, but being explicit keeps it correct if VITE_API_BASE points elsewhere.
const withCredentials: RequestInit = { credentials: "include" };

type Schemas = components["schemas"];

// The order status union comes straight from the backend enum:
// "Pending" | "Paid" | "Failed" | "Refunded".
export type OrderStatus = Schemas["OrderStatus"];

// The backend marks every field optional/nullable in its OpenAPI schema, but a
// persisted order always has them. This mapped type strips the "?" and null so
// callers get clean, definite fields — still derived entirely from the contract.
export type Order = { [K in keyof Schemas["Order"]]-?: NonNullable<Schemas["Order"][K]> };

export async function listOrders(): Promise<Order[]> {
  const res = await fetch(`${API_BASE}/orders`, withCredentials);
  if (!res.ok) throw new Error(`GET /orders failed: ${res.status}`);
  return res.json();
}

// What POST /orders returns (clientSecret is what Stripe.js needs to confirm).
// Derived from the contract now that the backend returns a named record.
export type CreateOrderResponse = { [K in keyof Schemas["CreateOrderResponse"]]-?: NonNullable<Schemas["CreateOrderResponse"][K]> };

// Delete one order. The backend requires ?confirm=true (guarded dev endpoint).
export async function deleteOrder(id: string): Promise<void> {
  const res = await fetch(`${API_BASE}/orders/${id}?confirm=true`, { method: "DELETE", ...withCredentials });
  if (!res.ok) throw new Error(`DELETE /orders/${id} failed: ${res.status}`);
}

// What POST /orders/{id}/refund returns (202): the request was accepted but the
// order is still pending — it flips to Refunded only on the charge.refunded webhook.
export type RefundResponse = { [K in keyof Schemas["RefundResponse"]]-?: NonNullable<Schemas["RefundResponse"][K]> };

// Refund a paid order. Returns the pending-refund body immediately; the order
// flips to Refunded only when the charge.refunded webhook arrives (see backend).
export async function refundOrder(id: string): Promise<RefundResponse> {
  const res = await fetch(`${API_BASE}/orders/${id}/refund`, { method: "POST", ...withCredentials });
  if (!res.ok) {
    const body = await res.json().catch(() => null);
    throw new Error(body?.error ?? `POST /orders/${id}/refund failed: ${res.status}`);
  }
  return res.json();
}

export async function createOrder(
  amountCents: number,
  currency: string,
): Promise<CreateOrderResponse> {
  const res = await fetch(`${API_BASE}/orders`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ amountCents, currency }),
    ...withCredentials,
  });
  if (!res.ok) {
    // Backend sends { error: "..." } on 400 — surface it.
    const body = await res.json().catch(() => null);
    throw new Error(body?.error ?? `POST /orders failed: ${res.status}`);
  }
  return res.json();
}

// --- Auth --------------------------------------------------------------------

// The signed-in user, derived from the backend's UserResponse contract.
export type AuthUser = { [K in keyof Schemas["UserResponse"]]-?: NonNullable<Schemas["UserResponse"][K]> };

// Sign in. Throws with the backend message on 401 (wrong credentials).
export async function login(email: string, password: string): Promise<AuthUser> {
  const res = await fetch(`${API_BASE}/auth/login`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ email, password }),
    ...withCredentials,
  });
  if (!res.ok) {
    const body = await res.json().catch(() => null);
    throw new Error(body?.error ?? "Invalid email or password.");
  }
  return res.json();
}

// Sign out. Clears the auth cookie server-side.
export async function logout(): Promise<void> {
  await fetch(`${API_BASE}/auth/logout`, { method: "POST", ...withCredentials });
}

// Current user, or null when signed out (the backend answers 401). Returning null
// instead of throwing lets the auth query model "logged out" as data, not error.
export async function getMe(): Promise<AuthUser | null> {
  const res = await fetch(`${API_BASE}/auth/me`, withCredentials);
  if (res.status === 401) return null;
  if (!res.ok) throw new Error(`GET /auth/me failed: ${res.status}`);
  return res.json();
}
