// Single place that knows where the backend lives. The data TYPES come from the
// backend's OpenAPI contract (src/api-types.ts, generated by `npm run gen:api`) —
// no hand-maintained copy that can silently drift from the API.

import type { components } from "./api-types";

export const API_BASE = "http://localhost:5144";

type Schemas = components["schemas"];

// The order status union comes straight from the backend enum:
// "Pending" | "Paid" | "Failed" | "Refunded".
export type OrderStatus = Schemas["OrderStatus"];

// The backend marks every field optional/nullable in its OpenAPI schema, but a
// persisted order always has them. This mapped type strips the "?" and null so
// callers get clean, definite fields — still derived entirely from the contract.
export type Order = { [K in keyof Schemas["Order"]]-?: NonNullable<Schemas["Order"][K]> };

export async function listOrders(): Promise<Order[]> {
  const res = await fetch(`${API_BASE}/orders`);
  if (!res.ok) throw new Error(`GET /orders failed: ${res.status}`);
  return res.json();
}

// What POST /orders returns (clientSecret is what Stripe.js needs to confirm).
// Derived from the contract now that the backend returns a named record.
export type CreateOrderResponse = { [K in keyof Schemas["CreateOrderResponse"]]-?: NonNullable<Schemas["CreateOrderResponse"][K]> };

// Delete one order. The backend requires ?confirm=true (guarded dev endpoint).
export async function deleteOrder(id: string): Promise<void> {
  const res = await fetch(`${API_BASE}/orders/${id}?confirm=true`, { method: "DELETE" });
  if (!res.ok) throw new Error(`DELETE /orders/${id} failed: ${res.status}`);
}

// What POST /orders/{id}/refund returns (202): the request was accepted but the
// order is still pending — it flips to Refunded only on the charge.refunded webhook.
export type RefundResponse = { [K in keyof Schemas["RefundResponse"]]-?: NonNullable<Schemas["RefundResponse"][K]> };

// Refund a paid order. Returns the pending-refund body immediately; the order
// flips to Refunded only when the charge.refunded webhook arrives (see backend).
export async function refundOrder(id: string): Promise<RefundResponse> {
  const res = await fetch(`${API_BASE}/orders/${id}/refund`, { method: "POST" });
  if (!res.ok) {
    const body = await res.json().catch(() => null);
    throw new Error(body?.error ?? `POST /orders/${id}/refund failed: ${res.status}`);
  }
  return res.json();
}

export async function createOrder(
  amountCents: number,
  currency: string,
): Promise<CreateOrderResponse> {
  const res = await fetch(`${API_BASE}/orders`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ amountCents, currency }),
  });
  if (!res.ok) {
    // Backend sends { error: "..." } on 400 — surface it.
    const body = await res.json().catch(() => null);
    throw new Error(body?.error ?? `POST /orders failed: ${res.status}`);
  }
  return res.json();
}
