// The data TYPES come from the backend's OpenAPI contract (src/api-types.ts,
// generated by `npm run gen:api`) via the Unwrap helper — no hand-maintained copy
// that can silently drift. All calls go through lib/http (cookies, timeout, error
// handling in one place).

import type { Schemas, Unwrap } from './lib/contract'
import { fetchJson, postJson, API_BASE } from './lib/http'

export { API_BASE }

// --- Orders ------------------------------------------------------------------

// The order status union comes straight from the backend enum:
// "Pending" | "Paid" | "Failed" | "Refunded".
export type OrderStatus = Schemas['OrderStatus']

// The admin order list (GET /orders) returns OrderResponse: the order fields plus
// the customer's email. customerEmail stays nullable (it's null for orders placed
// before accounts existed); the rest are always present on a listed order.
export type Order =
  Omit<Unwrap<Schemas['OrderResponse']>, 'customerEmail'>
  & { customerEmail: string | null }

// What POST /orders returns (clientSecret is what Stripe.js needs to confirm).
export type CreateOrderResponse = Unwrap<Schemas['CreateOrderResponse']>

// What POST /orders/{id}/refund returns (202): accepted but still pending — it
// flips to Refunded only on the charge.refunded webhook.
export type RefundResponse = Unwrap<Schemas['RefundResponse']>

export function listOrders(): Promise<Order[]> {
  return fetchJson<Order[]>('/orders')
}

export function createOrder(amountCents: number, currency: string): Promise<CreateOrderResponse> {
  return postJson<CreateOrderResponse>('/orders', { amountCents, currency })
}

export function refundOrder(id: string): Promise<RefundResponse> {
  return fetchJson<RefundResponse>(`/orders/${id}/refund`, { method: 'POST' })
}

// Delete one order. The backend requires ?confirm=true (guarded dev endpoint).
// Returns no body, so it doesn't go through fetchJson.
export async function deleteOrder(id: string): Promise<void> {
  const res = await fetch(`${API_BASE}/orders/${id}?confirm=true`, {
    method: 'DELETE',
    credentials: 'include',
  })
  if (!res.ok) throw new Error(`DELETE /orders/${id} failed: ${res.status}`)
}

// --- Auth --------------------------------------------------------------------

// The signed-in user, derived from the backend's UserResponse contract.
export type AuthUser = Unwrap<Schemas['UserResponse']>

// Sign in. Throws the backend message on 401 (wrong credentials).
export function login(email: string, password: string): Promise<AuthUser> {
  return postJson<AuthUser>('/auth/login', { email, password }, { fallbackError: 'Invalid email or password.' })
}

// Register a new customer account (signs in on success). Throws the backend
// message on 400/409 (invalid input / email taken).
export function register(email: string, password: string): Promise<AuthUser> {
  return postJson<AuthUser>('/auth/register', { email, password }, { fallbackError: 'Registration failed.' })
}

// Sign out. Clears the auth cookie server-side. Best-effort — ignore the result.
export async function logout(): Promise<void> {
  await fetch(`${API_BASE}/auth/logout`, { method: 'POST', credentials: 'include' })
}

// Current user, or null when signed out (the backend answers 401). Returning null
// instead of throwing lets the auth query model "logged out" as data, not error.
export async function getMe(): Promise<AuthUser | null> {
  const res = await fetch(`${API_BASE}/auth/me`, { credentials: 'include' })
  if (res.status === 401) return null
  if (!res.ok) throw new Error(`GET /auth/me failed: ${res.status}`)
  return res.json()
}
